### ISSUE TITLE
aide pour le menu déroulant

### ISSUE THREAD

**Issue by qvandekadsye** [Deuchnord/GL-PBA#1]
Bon voilà en fait je galère pour faire un menu déroulant alors j'aurais besoin d'aide.

**Comment by Deuchnord** [comment]
En fait, pour les menus déroulants (_dropdowns_), Bootstrap utilise JavaScript¹. Il faut donc charger JQuery et le fichier `bootstrap/js/bootstrap.min.js` et utiliser [ceci](http://getbootstrap.com/javascript/#dropdowns).

¹ Oui, c'est débile.
