### ISSUE TITLE
Problème au niveau de la page paypal du don en ligne paypal.

### ISSUE THREAD

**Issue by qvandekadsye** [Deuchnord/GL-PBA#2]
Ce n'est pas vraiment un problème de programmation mais plutot un problème technique. Paypal refuse maintenant que l'on puisse faire un don sans avoir lié une carte. Du coup, je peux pas copié la page pour la maquette.

**Comment by Deuchnord** [comment]
Ah, c'est nouveau ça, non ?

Au pire, si vraiment ça fait chier, on peut toujours mettre une page intermédiaire signalant simplement que l'on redirige par PayPal/autre, avec un lien vers la page suivante, non ?
